# Generated by Django 3.0.5 on 2020-04-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/blog/images'),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
