# Generated by Django 3.0.5 on 2020-04-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200418_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='title',
            field=models.CharField(blank=True, default='foobar', max_length=100),
        ),
    ]
