# Generated by Django 3.0.5 on 2020-04-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200430_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='title',
            field=models.CharField(blank=True, default='Sanjeev', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='url',
            field=models.URLField(),
        ),
    ]
