# Generated by Django 3.0.5 on 2020-04-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200430_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
